events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        listen 443 ssl;
        server_name localhost;

        # SSL Certificates
        ssl_certificate /etc/nginx/ssl/cert.pem;
        ssl_certificate_key /etc/nginx/ssl/key.pem;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            
            # This is the magic line that makes Angular routing work!
            try_files $uri $uri/ /index.html;
        }
    }
}