apiVersion: apps/v1
kind: Deployment
metadata:
  name: blufountain-dashboard-deployment
  namespace: blufountain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blufountain-dashboard
  template:
    metadata:
      labels:
        app: blufountain-dashboard
    spec:
      containers:
      - name: blufountain-dashboard-container
        image: munerielvis/blufountain-dashboard:latest
        ports:
        - containerPort: 80   # NGINX HTTP port
        - containerPort: 3000 # App HTTP port
        - containerPort: 443  # NGINX HTTPS port