apiVersion: v1
kind: Service
metadata:
  name: blufountain-dashboard-svc
  namespace: blufountain
spec:
  type: NodePort
  selector:
    app: blufountain-dashboard
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
    # ⚠️ CRITICAL: I changed this from 30809 to 30810 to prevent a crash!
    nodePort: 30810